name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          # Save the private and public keys
          echo "$SSH_PRIVATE_KEY" > ssh_key
          echo "$SSH_PUBLIC_KEY" > ssh_key.pub
          chmod 600 ssh_key ssh_key.pub

          # Deploy with rsync using the private key
          rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" ./dist/ "$VPS_USERNAME@$VPS_IP:$VPS_PATH"

          # Cleanup
          rm -f ssh_key ssh_key.pub
